const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Prepare report",
        taskDescription: "Compile the quarterly sales data into a report.",
        taskDate: "2025-05-14",
        category: "Reports",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix login bug",
        taskDescription: "Resolve the login issue affecting some users.",
        taskDate: "2025-05-12",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Team meeting",
        taskDescription: "Attend weekly sync-up with the product team.",
        taskDate: "2025-05-15",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Sneha",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Write documentation",
        taskDescription: "Document the API endpoints for the new feature.",
        taskDate: "2025-05-13",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Client call",
        taskDescription: "Discuss project requirements with the client.",
        taskDate: "2025-05-14",
        category: "Communication",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Code review",
        taskDescription: "Review pull requests submitted by the team.",
        taskDate: "2025-05-12",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix styling issues",
        taskDescription: "Resolve CSS bugs on the landing page.",
        taskDate: "2025-05-11",
        category: "Design",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 3,
    firstName: "Rohan",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      active: 3,
      newTask: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Update dependencies",
        taskDescription: "Upgrade all outdated npm packages.",
        taskDate: "2025-05-10",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "User feedback analysis",
        taskDescription: "Analyze recent feedback and compile findings.",
        taskDate: "2025-05-13",
        category: "Research",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix search bug",
        taskDescription: "Resolve issue with search bar not returning results.",
        taskDate: "2025-05-14",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Run tests",
        taskDescription: "Execute automated test suite on new release.",
        taskDate: "2025-05-12",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Deploy update",
        taskDescription: "Deploy the latest version to staging.",
        taskDate: "2025-05-15",
        category: "Deployment",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Meera",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Organize files",
        taskDescription: "Clean and organize internal project files.",
        taskDate: "2025-05-09",
        category: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Prepare slides",
        taskDescription: "Create presentation slides for the meeting.",
        taskDate: "2025-05-14",
        category: "Presentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Security audit",
        taskDescription: "Conduct a quick audit of system security.",
        taskDate: "2025-05-13",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Schedule interviews",
        taskDescription: "Set up interviews for the developer position.",
        taskDate: "2025-05-11",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Kunal",
    email: "employee5@example.com",
    password: "123",
    taskCounts: {
      active: 3,
      newTask: 2,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Design logo",
        taskDescription: "Create a new logo for marketing campaign.",
        taskDate: "2025-05-14",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Write blog post",
        taskDescription: "Draft a blog post on company culture.",
        taskDate: "2025-05-10",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "SEO analysis",
        taskDescription: "Analyze site SEO and report improvements.",
        taskDate: "2025-05-13",
        category: "SEO",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Backup database",
        taskDescription: "Create a backup before major update.",
        taskDate: "2025-05-11",
        category: "Database",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Plan webinar",
        taskDescription: "Organize logistics and promotion for the webinar.",
        taskDate: "2025-05-15",
        category: "Events",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Product demo",
        taskDescription: "Present product demo to potential clients.",
        taskDate: "2025-05-12",
        category: "Sales",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
